server:
  port: 7001


eureka:
  instance:
    hostname: localhost #euraka服务的实例名字
  client:
    register-with-eureka: false #表示不向注册中心注册自己
    fetch-registry: false #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      #设置于eureka server交互的地址查询服务和注册服务都依赖这个地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/